FROM denley/ubuntu:base
MAINTAINER Denley Hsiao <denley@justtodo.com>

# 安装docker/docker-compose
RUN curl -k -sSl https://get.docker.com | sudo sh
RUN sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose \
  && sudo chmod +x /usr/local/bin/docker-compose
