FROM denley/dev_python
MAINTAINER Denley Hsiao <denley@justtodo.com>

RUN source $HOME/.bash_profile \ 
  && pip install --upgrade pip \
  && pip install --upgrade numpy scipy sklearn matplotlib pillow \
  && pip install --upgrade tensorflow
