FROM denley/ubuntu
MAINTAINER Denley Hsiao <denley@justtodo.com>

# 安装nvm/nodejs		
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash -s stable \		
  && source $HOME/.nvm/nvm.sh \		
  && nvm install stable
